### ISSUE TITLE
get_push_path

### ISSUE THREAD

**Issue by Dionysus7777777** [m-abr/FCPCodebase#9] opened 2024-03-28 08:59 UTC
what is the difference between get_push_path and get_dribble_path in pathmanager

**Comment by m-abr** [comment] 2024-03-29 01:12
`get_dribble_path` was designed for the dribble behavior that is included in the codebase release. `get_push_path` was designed for a push behavior, which is not included. The push behavior is essentially a slow moving dribble with push-recovery abilities for scenarios where collisions are likely to occur.

The following table provides more details about the differences between the default behaviors of each method:

|  | **get_dribble_path** | **get_push_path** |
| --- | --- | ----------- |
| teammates are obstacles | True | False |
| opponents are obstacles | True | False |
| max obstacle distance | 5 m | 4 m |
| max obstacle age <sup>1</sup> | 1 s | 0.5 s |  
| goalposts safety margin | 0.4 m | 0 m |
| hot start <sup>2</sup> | Yes | No |
| returned segments <sup>3</sup> | 2 | 1.5 |
| returned parameters <sup>4</sup> | next position, next orientation | next position |

<sup>1</sup> maximum time since obstacle was last seen (otherwise it is ignored)

<sup>2</sup> 'hot start' means that the path for dribbling starts slightly ahead of the robot instead of its current position, predicting where the robot will be in the next time steps, regardless of the current path decision, due to relatively long reaction times. This mitigates some trajectory noise while the robot is moving at a fast pace with dynamic obstacles.

<sup>3</sup> The path computed through the custom A* algorithm uses a grid with a resolution of 0.1 m. Therefore, the path is composed of small segments with 0.1 m or 0.14 m (diagonal segment). The returned next target position is one of the points of this discrete path. The `ret_segments` variable indicates the number of segments between the robot's current position, and the next target position.

<sup>4</sup> The returned parameters is just a matter of convenience. For dribbling, it is more convenient to know the dribble direction instead of the next target position. So, although the position is also returned, it is not used for dribbling. 

---

`get_dribble_path` also uses `mode = Path_Manager.MODE_DRIBBLE` which increases the safety radius around obstacles since the robot moves quickly while dribbling.

**Comment by Dionysus7777777** [comment] 2024-03-31 11:13
In what situations is it better to use "push"? Is it in front of the door?
If I need to use it, do I need to create another function?

**Comment by m-abr** [comment] 2024-03-31 22:46
As mentioned in the previous message, the code release does not include the push behavior. Therefore, you have two options: you can either develop your own push behavior or manually walk towards the ball to push it where you want it to go.

If you choose the latter option, I suggest referring to the _Getting Started_ section of the [documentation](https://docs.google.com/document/d/1aJhwK2iJtU-ri_2JOB8iYvxzbPskJ8kbk_4rb3IK3yc/edit#heading=h.k2aha3pudnm6), particularly Sections 4.1 and 4.2. These sections provide a step-by-step guide on how to push the ball in the direction of the opponent's goal simply by walking towards it.

**Comment by Dionysus7777777** [comment] 2024-04-01 07:55
I'm very grateful for your patient answers

**Closed** 2024-04-01 07:58 UTC
